//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayaGameLauncher.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<decimal> TransCost { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> IDOrderGame { get; set; }
    
        public virtual OrderGame OrderGame { get; set; }
        public virtual User User { get; set; }
    }
}
