//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayaGameLauncher.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagOfUser
    {
        public int ID { get; set; }
        public int TagID { get; set; }
        public int UserID { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
